AppsCollection = 'unique_applications'
AppsPerAgentCollection = 'apps_per_agent'
CustomAppsCollection = 'custom_apps'
CustomAppsPerAgentCollection = 'custom_apps_per_agent'
SupportedAppsCollection = 'supported_apps'
SupportedAppsPerAgentCollection = 'supported_apps_per_agent'
AgentAppsCollection = 'agent_apps'
AgentAppsPerAgentCollection = 'agent_apps_per_agent'
LatestDownloadedSupportedCollection = 'latest_downloaded_supported'
LatestDownloadedAgentCollection = 'latest_downloaded_agent'
FilesCollection = 'files'

ALL_APP_COLLECTIONS = ('apps', 'custom_apps', 'supported_apps', 'agent_apps')
Id = 'id'
PerAgentCollection = '_per_agent'
PerTagCollection = '_per_tag'
AGENTID = 'agent_id'
AgentIdAndTagId = 'agentid_and_tagid'
COUNT = 'count'
AGENT_COUNT = 'agent_count'
AGENTS = 'agents'
STATUS = 'status'
NAME = 'name'
VERSION = 'version'
INSTALLED = 'installed'
AVAILABLE = 'available'
SOFTWAREINVENTORY = 'Software Inventory'
OS = 'OS'
CUSTOM = 'Custom'
SUPPORTED = 'Supported'
PENDING = 'pending'
AGENT_UPDATES = 'Agent Updates'
APP_ID = 'app_id'
APP_NAME = 'app_name'
APP_URIS = 'app_uris'
PKG_NAME = 'file_name'
PKG_SIZE = 'file_size'
PKG_URI = 'file_uri'
FILE_URIS = 'file_uris'
PKG_HASH = 'file_hash'
PKG_URIS = 'uris'
PKG_FILEDATA = 'file_data'
PKG_CLI_OPTIONS = 'cli_options'
YES = 'yes'
NO = 'no'
ValidPackageStatuses = (INSTALLED, AVAILABLE, PENDING)
ValidHiddenVals = (YES, NO)

CRITICAL = 'Critical'
OPTIONAL = 'Optional'
RECOMMENDED = 'Recommended'
ValidRvSeverities = (CRITICAL, RECOMMENDED, OPTIONAL)
BASIC_RV_STATS = 'basic_rv_stats'


class FilesKey():
    AppId = 'app_id'
    AppIds = 'app_ids'
    AgentIds = 'agent_ids'
    FileName = 'file_name'
    FileSize = 'file_size'
    FileUri = 'file_uri'
    FileHash = 'file_hash'
    FilesDownloadStatus = 'files_download_status'


class FilesIndexes():
    AppId = 'app_id'
    FilesDownloadStatus = 'files_download_status'


class AppsKey():
    AppId = 'app_id'
    Customers = 'customers'
    Name = 'name'
    Hidden = 'hidden'
    Description = 'description'
    ReleaseDate = 'release_date'
    RebootRequired = 'reboot_required'
    Kb = 'kb'
    FileSize = 'file_size'
    FileData = 'file_data'
    SupportUrl = 'support_url'
    Version = 'version'
    OsCode = 'os_code'
    RvSeverity = 'rv_severity'
    VendorSeverity = 'vendor_severity'
    VendorName = 'vendor_name'
    FilesDownloadStatus = 'files_download_status'
    VulnerabilityId = 'vulnerability_id'
    VulnerabilityCategories = 'vulnerability_categories'
    CveIds = 'cve_ids'


class AppsIndexes():
    AppId = 'app_id'
    Name = 'name'
    RvSeverity = 'rv_severity'
    AppIdAndRvSeverity = 'appid_and_rv_severity'
    NameAndVersion = 'name_and_version'
    Customers = 'customers'
    CustomerAndRvSeverity = 'customer_and_rvseverity'
    AppIdAndRvSeverityAndHidden = 'appid_and_rv_severity_and_hidden'
    AppIdAndHidden = 'appid_and_hidden'
    CustomerAndHidden = 'customer_and_hidden'


class AppsPerAgentKey():
    AppId = 'app_id'
    Id = 'id'
    InstallDate = 'install_date'
    Status = 'status'
    Hidden = 'hidden'
    AgentId = 'agent_id'
    CustomerName = 'customer_name'
    Dependencies = 'dependencies'
    LastModifiedTime = 'last_modified_time'
    Update = 'update'
    CveIds = 'cve_ids'


class AppsPerAgentIndexes():
    AppId = 'app_id'
    AgentId = 'agent_id'
    Status = 'status'
    CustomerName = 'customer_name'
    AppIdAndStatus = 'appid_and_status'
    AgentIdAndAppId = 'agentid_and_appid'
    AppIdAndCustomer = 'appid_and_customer'
    StatusAndAgentId = 'status_and_agentid'
    AppIdStatusAndAgentId = 'appid_and_status_and_agentid'
    StatusAndCustomer = 'status_and_customer'
    StatusAndCveId = 'status_and_cve_id'
    AppIdAndStatusAndCustomer = 'appid_and_status_and_customer'


class CustomAppsKey():
    AppId = 'app_id'
    Customers = 'customers'
    RvId = 'rv_id'
    Name = 'name'
    Hidden = 'hidden'
    CustomerName = 'customer_name'
    Description = 'description'
    ReleaseDate = 'release_date'
    Kb = 'kb'
    FileSize = 'file_size'
    FileData = 'file_data'
    FilesVerified = 'files_verified'
    FilesDownloadStatus = 'files_download_status'
    RebootRequired = 'reboot_required'
    SupportUrl = 'support_url'
    Version = 'version'
    MajorVersion = 'major_version'
    MinorVersion = 'minor_version'
    OsCode = 'os_code'
    RvSeverity = 'rv_severity'
    VendorSeverity = 'vendor_severity'
    VendorName = 'vendor_name'
    CliOptions = 'cli_options'
    Arch = 'arch'
    VulnerabilityId = 'vulnerability_id'
    VulnerabilityCategories = 'vulnerability_categories'
    CveIds = 'cve_ids'


class CustomAppsIndexes():
    AppId = 'app_id'
    Name = 'name'
    RvSeverity = 'rv_severity'
    AppIdAndRvSeverity = 'appid_and_rv_severity'
    NameAndVersion = 'name_and_version'
    Customers = 'customers'
    CustomerAndRvSeverity = 'customer_and_rvseverity'
    AppIdAndRvSeverityAndHidden = 'appid_and_rv_severity_and_hidden'
    AppIdAndHidden = 'appid_and_hidden'
    CustomerAndHidden = 'customer_and_hidden'


class CustomAppsPerAgentKey():
    Id = 'id'
    AppId = 'app_id'
    CustomerName = 'customer_name'
    Name = 'name'
    InstallDate = 'install_date'
    Status = 'status'
    Hidden = 'hidden'
    AgentId = 'agent_id'
    Dependencies = 'dependencies'
    LastModifiedTime = 'last_modified_time'
    Update = 'update'
    CveIds = 'cve_ids'


class CustomAppsPerAgentIndexes():
    AppId = 'app_id'
    AgentId = 'agent_id'
    Status = 'status'
    CustomerName = 'customer_name'
    AppIdAndStatus = 'appid_and_status'
    AgentIdAndAppId = 'agentid_and_appid'
    AppIdAndCustomer = 'appid_and_customer'
    StatusAndAgentId = 'status_and_agentid'
    StatusAndCustomer = 'status_and_customer'
    StatusAndCveId = 'status_and_cve_id'
    AppIdAndStatusAndCustomer = 'appid_and_status_and_customer'


class SupportedAppsKey():
    AppId = 'app_id'
    Customers = 'customers'
    RvId = 'rv_id'
    Name = 'name'
    Hidden = 'hidden'
    Description = 'description'
    ReleaseDate = 'release_date'
    Kb = 'kb'
    FileSize = 'file_size'
    FileData = 'file_data'
    FilesVerified = 'files_verified'
    FilesDownloadStatus = 'files_download_status'
    RebootRequired = 'reboot_required'
    SupportUrl = 'support_url'
    Version = 'version'
    MajorVersion = 'major_version'
    MinorVersion = 'minor_version'
    OsCode = 'os_code'
    RvSeverity = 'rv_severity'
    VendorSeverity = 'vendor_severity'
    VendorName = 'vendor_name'
    CliOptions = 'cli_options'
    Arch = 'arch'
    VulnerabiltyId = 'vulnerability_id'
    VulnerabiltyCategories = 'vulnerability_categories'
    CveIds = 'cve_ids'


class SupportedAppsIndexes():
    AppId = 'app_id'
    Name = 'name'
    CustomerName = 'customer_name'
    RvSeverity = 'rv_severity'
    AppIdAndRvSeverity = 'appid_and_rv_severity'
    NameAndVersion = 'name_and_version'
    Customers = 'customers'
    CustomerAndRvSeverity = 'customer_and_rvseverity'
    AppIdAndRvSeverityAndHidden = 'appid_and_rv_severity_and_hidden'
    AppIdAndHidden = 'appid_and_hidden'
    CustomerAndHidden = 'customer_and_hidden'


class SupportedAppsPerAgentKey():
    Id = 'id'
    AppId = 'app_id'
    Name = 'name'
    InstallDate = 'install_date'
    Status = 'status'
    Hidden = 'hidden'
    AgentId = 'agent_id'
    CustomerName = 'customer_name'
    Dependencies = 'dependencies'
    LastModifiedTime = 'last_modified_time'
    Update = 'update'
    CveIds = 'cve_ids'


class SupportedAppsPerAgentIndexes():
    AppId = 'app_id'
    AgentId = 'agent_id'
    Status = 'status'
    CustomerName = 'customer_name'
    AppIdAndStatus = 'appid_and_status'
    AgentIdAndAppId = 'agentid_and_appid'
    AppIdAndCustomer = 'appid_and_customer'
    StatusAndAgentId = 'status_and_agentid'
    StatusAndCustomer = 'status_and_customer'
    StatusAndCveId = 'status_and_cve_id'
    AppIdAndStatusAndCustomer = 'appid_and_status_and_customer'


class AgentAppsKey():
    AppId = 'app_id'
    Customers = 'customers'
    RvId = 'rv_id'
    Name = 'name'
    Hidden = 'hidden'
    Description = 'description'
    ReleaseDate = 'release_date'
    Kb = 'kb'
    FileSize = 'file_size'
    FileData = 'file_data'
    FilesVerified = 'files_verified'
    FilesDownloadStatus = 'files_download_status'
    RebootRequired = 'reboot_required'
    SupportUrl = 'support_url'
    Version = 'version'
    MajorVersion = 'major_version'
    MinorVersion = 'minor_version'
    OsCode = 'os_code'
    RvSeverity = 'rv_severity'
    VendorSeverity = 'vendor_severity'
    VendorName = 'vendor_name'
    CliOptions = 'cli_options'
    Arch = 'arch'
    VulnerabiltyId = 'vulnerability_id'
    VulnerabiltyCategories = 'vulnerability_categories'
    CveIds = 'cve_ids'


class AgentAppsIndexes():
    AppId = 'app_id'
    Name = 'name'
    CustomerName = 'customer_name'
    RvSeverity = 'rv_severity'
    AppIdAndRvSeverity = 'appid_and_rv_severity'
    NameAndVersion = 'name_and_version'
    Customers = 'customers'
    CustomerAndRvSeverity = 'customer_and_rvseverity'
    AppIdAndRvSeverityAndHidden = 'appid_and_rv_severity_and_hidden'
    AppIdAndHidden = 'appid_and_hidden'
    CustomerAndHidden = 'customer_and_hidden'


class AgentAppsPerAgentKey():
    Id = 'id'
    AppId = 'app_id'
    CustomerName = 'customer_name'
    Dependencies = 'dependencies'
    Name = 'name'
    InstallDate = 'install_date'
    Status = 'status'
    Hidden = 'hidden'
    AgentId = 'agent_id'
    LastModifiedTime = 'last_modified_time'
    Update = 'update'
    CveIds = 'cve_ids'


class AgentAppsPerAgentIndexes():
    AppId = 'app_id'
    AgentId = 'agent_id'
    Status = 'status'
    CustomerName = 'customer_name'
    AppIdAndStatus = 'appid_and_status'
    AgentIdAndAppId = 'agentid_and_appid'
    AppIdAndCustomer = 'appid_and_customer'
    StatusAndAgentId = 'status_and_agentid'
    StatusAndCustomer = 'status_and_customer'
    StatusAndCveId = 'status_and_cve_id'
    AppIdAndStatusAndCustomer = 'appid_and_status_and_customer'

